version: '2'

services:
    # Central nginx proxy
    reverseproxy:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - 80:80
            - 443:443
        restart: always

    # My oublawness
    myoublawness:
        depends_on:
            - reverseproxy
        image: myoublawness:latest
        restart: always

    myoublawness_beta:
        depends_on:
            - reverseproxy
        image: myoublawness:beta
        restart: always
