version: '2'

services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 80:80
            - 443:443
        restart: always

    myoublawness:
        depends_on:
            - reverseproxy
        image: myoublawness:latest
        restart: always

    myoublawness_beta:
        depends_on:
            - reverseproxy
        image: myoublawness:beta
        restart: always