version: '2'

services:
    # Central nginx proxy
    reverseproxy:
        image: reverseproxy
        ports:
            - 80:80
            - 443:443
        restart: always

    # My oublawness
    myoublawness:
        depends_on:
            - reverseproxy
        image: myoublawness:latest
        restart: always

    myoublawness_beta:
        depends_on:
            - reverseproxy
        image: myoublawness:beta
        restart: always
    
    # Katrina's part
    mysql:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=df52e715326891f20d4c85e946ce9108cf66228ca31a92e9
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
        restart: always
        volumes:
            - /sessions
        depends_on:
            - mysql
